### ISSUE TITLE
Gitter or Slack?

### ISSUE THREAD

**Issue by warengonzaga** [WarenGonzaga/AnimateCSSPlugin#6]
I want an active communication between users and developers. So we can discuss any topics related to this project. We have already gitter account... how about slack?

@SakhirAtwi what do you think?

**Comment by SakhirAtwi** [comment]
@WarenGonzaga good to hear from you, sad but I don't have account any of those right now :P. But I have worked on slack, I guess it has proved its durability over the past, I have never worked with gitter so can't say anything about that. I would say slack is the way to go, but don't want to degrade gitter either.

**Comment by SakhirAtwi** [comment]
@WarenGonzaga I wanted to say three things, first I wanted to mention that the official pages site [Demo site of project](https://warengonzaga.github.io/sites/animatecssplugin.html) is still running the older version, you have got to update that.

Second, I was thinking that after the stable release of the plugin which would happen in a day or two we should contact someone on the GSAP mailing list so that we can ask them to add the plugin in the official cdnjs so that people can know about the plugin and use it to actual work.

Third, I wanted to ask you if I can credit myself in the Readme file and inside the code comments(my email), of couse the project belongs to you and I can't do that without your permission.


Cheers :) Happy coding.

**Comment by warengonzaga** [comment]
@SakhirAtwi alright let's talk about inside slack about your third thing...

for the first thing you mention, will be update the demo site after the official stable release... I found a bug in your jello animation it is skew in wrong place... please double check that...

the second thing, let's make it happen if possible since I already told them about it and they suggest that we should have own support for the plugin because they want a plugin that they created so that they can easily support users... also they mention that it is hard to support a plugin if you are not the maker or the developer...

**Comment by warengonzaga** [comment]
@SakhirAtwi can you please send me your email here: warengonzaga.dev@gmail.com also please include your full name there.

**Comment by SakhirAtwi** [comment]
Sent you a mail, check it out.

**Comment by SakhirAtwi** [comment]
@WarenGonzaga you got the email right?

**Comment by warengonzaga** [comment]
@SakhirAtwi yes I got your email... will inform you through email...
